Yazhini/feature/design fixes
calibraint-ch/curvex pull request #9
Opened 2023-06-19 16:20 UTC by Yazhinivenkatesh

This PR has the following:

-> Completed remaining launchpad section
-> Updated Landing page and Appscreen designs
-> Changes on routes and connect wallet feature

2023-06-19 17:51 UTC, nandhabn requested changes

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/components/Header/Header.tsx
> +                  <DownOutlined />
Inner condition might not be required since it is checked on the outer condition. Please Check and update.

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/containers/AppScreen/index.tsx
> +  console.log(tabOptions, "Tab............")
Check the console log

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/containers/UserDashboard/index.tsx
> +    console.log(walletAddress);
Check the console log

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/customHooks/useMetamaskProvider.tsx
> +  }
Can we use `metastate.web3.provider` instead of the window.Ethereum.

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/components/Header/Header.tsx
> +              <Link style={{ textDecoration: "none" }} to={"/dashboard"}>
Use constant from routes file

2023-06-19 17:51 UTC, nandhabn commented on frontend/src/app/components/Header/Header.tsx
> +                <div>Dashboard</div>
Here as well.

2023-06-20 05:08 UTC, Yazhinivenkatesh commented on frontend/src/app/components/Header/Header.tsx
> +                  <DownOutlined />
Will change

2023-06-20 05:09 UTC, Yazhinivenkatesh commented on frontend/src/app/containers/AppScreen/index.tsx
> +  console.log(tabOptions, "Tab............")
okay

2023-06-20 05:10 UTC, Yazhinivenkatesh commented on frontend/src/app/customHooks/useMetamaskProvider.tsx
> +  }
It is not working as expected, it takes some time to detect network change.

2023-06-20 05:11 UTC, Yazhinivenkatesh commented on frontend/src/app/components/Header/Header.tsx
> +              <Link style={{ textDecoration: "none" }} to={"/dashboard"}>
Done

2023-06-21 04:56 UTC, gowtham-calib approved these changes

2023-06-21 04:56 UTC, nandhabn approved these changes

2023-06-21 04:56 UTC, merged